SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6918EE7B70DA27A2}" {
     m_sEntityPrefab "{2B8E5F1C904D73A9}Prefabs/Items/Medicine/CombatStimInjection_01/CombatStimInjection_01.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{5C62F7D80D4C5D03}" {
       m_eItemType HEAL
       m_eItemMode CONSUMABLE
       m_iSupplyCost 3
      }
     }
    }
   }
  }
 }
}