SCR_ArsenalItemListConfig {
 m_aArsenalItems {
  SCR_ArsenalItemStandalone "{6912C5660AC31CFF}" {
   m_eItemType EQUIPMENT
   m_iSupplyCost 0
   m_ItemResourceName "{983B57B8E95C1F52}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded_FIA.et"
  }
  SCR_ArsenalItemStandalone "{6912C5660AC31CEF}" {
   m_eItemType EQUIPMENT
   m_iSupplyCost 0
   m_ItemResourceName "{922F95F91943F69A}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded_US.et"
  }
  SCR_ArsenalItemStandalone "{6912C5660AC31CE9}" {
   m_eItemType EQUIPMENT
   m_iSupplyCost 0
   m_ItemResourceName "{F849217AB3BA88BE}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded_USSR.et"
  }
  SCR_ArsenalItemStandalone "{6912C5660AC31CEB}" {
   m_eItemType EQUIPMENT
   m_iSupplyCost 0
   m_ItemResourceName "{7CEF68E2BC68CE71}Prefabs/Items/Equipment/Compass/Compass_Adrianov.et"
  }
  SCR_ArsenalItemStandalone "{6912C5660AC31C94}" {
   m_eItemType EQUIPMENT
   m_iSupplyCost 0
   m_ItemResourceName "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et"
  }
  SCR_ArsenalItemStandalone "{D0F6A2C45E708B63}" {
   m_eItemType EQUIPMENT
   m_iSupplyCost 0
   m_ItemResourceName "{630FB4AD4A735264}Prefabs/Items/Equipment/Canteens/Canteen_US_01.et"
  }
  SCR_ArsenalItemStandalone "{D0F6A2C45E708B64}" {
   m_eItemType EQUIPMENT
   m_iSupplyCost 0
   m_ItemResourceName "{70BC751317551D9B}Prefabs/Items/Equipment/Canteens/Canteen_Soviet_01.et"
  }
  SCR_ArsenalItemStandalone "{6912C5660AC31C95}" {
   m_eItemType EQUIPMENT
   m_iSupplyCost 0
   m_ItemResourceName "{062E2F1D7F6739D6}Prefabs/Items/Equipment/Accessories/ETool_MPL50/ETool_MPL50_FreeRoamBuilding_Gadget.et"
  }
  SCR_ArsenalItemStandalone "{6912C5660AC31C97}" {
   m_eItemType EQUIPMENT
   m_iSupplyCost 0
   m_ItemResourceName "{6E35D94130954509}Prefabs/Items/Equipment/Accessories/ETool_ALICE/ETool_ALICE_FreeRoamBuilding_Gadget.et"
  }
 }
}